version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=n8n.konfortes.uk
      - N8N_PORT=5678
      - WEBHOOK_URL=https://n8n.konfortes.uk/
      - NODE_ENV=production
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      # Database configuration
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n
      # Queue configuration
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
    volumes:
      - n8n_data:/home/node/.n8n
      - ./workflows:/home/node/workflows
    networks:
      - n8n-network
    depends_on:
      - postgres
      - redis

  n8n-worker:
    image: n8nio/n8n
    restart: always
    environment:
      - NODE_ENV=production
      - N8N_RUNNERS_ENABLED=true
      # Database configuration
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n
      # Queue configuration
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      # Worker specific settings
      - N8N_MODE=worker
    networks:
      - n8n-network
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=n8n
      - POSTGRES_DB=n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - n8n-network

  redis:
    image: redis:6-alpine
    restart: always
    networks:
      - n8n-network

volumes:
  n8n_data:
    name: n8n_data
  postgres_data:
    name: n8n_postgres_data

networks:
  n8n-network:
    name: n8n-network 
